
version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  # Spring Boot
  spring-app:
    build:
      context: ./okintern3  # Path to your Spring Boot app's Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: 
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:

volumes:
  mariadb-data: