spring:
  datasource:
    url: ENC(bziqFvKm0CWkgmSZpfheYN43UshlxWQWsAIS+oLcHAhc38jtrqWPRsDQqJaqRVWW1+bD2xka4bY0f/7HnskB+ez97rm8GmuZUnSq0sHL5u4=)
    username: ENC(qu/hd95zEjlY7KwnmLJdVA==)
    password: ENC(qa3/SyitnaOZJA6Ts+STxQ==)
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # Set to true to show SQL queries in logs (for debugging)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace

jasypt:
  encryptor:
    bean: jasyptStringEncryptor